"""API routes for devcontainer generation, versioning, and download."""
from __future__ import annotations

import io
import json
import textwrap
import zipfile
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.api.routes.auth import get_current_user
from app.core.database import get_rls_db as get_db
from app.models.analysis_job import AtlasJob
from app.models.analysis_result import AtlasResult
from app.models.devcontainer import Devcontainer
from app.schemas.devcontainer import (
    DevcontainerListResponse,
    DevcontainerRequest,
    DevcontainerResponse,
    DevcontainerVersionResponse,
)
from app.services.audit_service import AuditService
from app.services.devcontainer_generator import DevcontainerGenerator
from app.services.summary_service import generate_devcontainer_config
from app.utils.field_encryption import decrypt_json
from app.utils.secret_detector import SecretDetector

router = APIRouter(prefix="/api/devcontainer", tags=["devcontainer"])


# ── Stack extraction helpers ──────────────────────────────────────────────────

def _languages_from_stack(detected_stack: dict) -> list[str]:
    """Map detected_stack backend/frontend framework names to language identifiers."""
    lang_map = {
        "FastAPI": "python", "Django": "python", "Flask": "python",
        "Next.js": "node", "React": "node", "Vue": "node", "Svelte": "node",
        "Express": "node", "TypeScript": "node",
        "Go": "go", "Gin": "go", "Echo": "go",
        "Spring": "java", "Rust": "rust",
    }
    langs: list[str] = []
    for category in ("backend", "frontend", "runtime"):
        for item in detected_stack.get(category, []):
            name = item.get("name", "") if isinstance(item, dict) else item
            lang = lang_map.get(name)
            if lang and lang not in langs:
                langs.append(lang)
    return langs or ["python"]


def _frameworks_from_stack(detected_stack: dict) -> list[str]:
    """Extract lower-cased framework names from detected_stack."""
    seen: list[str] = []
    for category in ("backend", "frontend"):
        for item in detected_stack.get(category, []):
            name = item.get("name", "") if isinstance(item, dict) else item
            key = name.lower().replace(".", "").replace("-", "")  # "Next.js" → "nextjs"
            if name and key not in seen:
                seen.append(key)
    return seen


# ── ZIP builder ───────────────────────────────────────────────────────────────

_SETUP_TEMPLATE = textwrap.dedent("""\
    #!/usr/bin/env bash
    # Auto-generated by Atlas Devcontainer Generator
    set -euo pipefail

    {body}

    echo "✓ Atlas devcontainer setup complete"
""")


def _build_setup_sh(config: dict) -> str:
    cmd = config.get("postCreateCommand", "")
    lines = [c.strip() for c in cmd.split("&&") if c.strip()] if cmd else []
    body = "\n".join(lines) if lines else 'echo "No post-create commands defined."'
    return _SETUP_TEMPLATE.format(body=body)


def _build_zip(config: dict, version: int) -> io.BytesIO:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(".devcontainer/devcontainer.json", json.dumps(config, indent=2))
        zf.writestr(".devcontainer/setup.sh", _build_setup_sh(config))
        zf.writestr(
            "README.md",
            f"# Atlas Devcontainer (v{version})\n\n"
            "Open this folder in VS Code and click **Reopen in Container**, "
            "or push to GitHub and launch a Codespace from the repository page.\n",
        )
    buf.seek(0)
    return buf


# ── Config generator (LLM with deterministic fallback) ────────────────────────

_logger = __import__("logging").getLogger(__name__)


async def _build_config_dict(
    evidence: dict | None,
    languages: list[str],
    frameworks: list[str],
    services: list[str],
    custom_features: list[str],
) -> dict:
    """Try the LLM path; fall back to the deterministic generator on any failure.

    All LLM output is secret-masked before being returned.
    """
    if evidence:
        try:
            raw = await generate_devcontainer_config(evidence)
            # Mask any secrets Claude may have echoed from README / env examples
            for field in ("postCreateCommand", "containerEnv"):
                if isinstance(raw.get(field), str):
                    raw[field] = SecretDetector.mask_all_secrets(raw[field])
            raw.setdefault("remoteUser", "vscode")
            _logger.info("devcontainer_llm_generation_success")
            return raw
        except Exception as exc:
            _logger.warning("devcontainer_llm_generation_failed: %s — using deterministic fallback", exc)

    config = DevcontainerGenerator.generate(
        languages=languages,
        frameworks=frameworks,
        services=services,
        custom_features=custom_features,
    )
    return DevcontainerGenerator.to_json(config)


# ── Routes ────────────────────────────────────────────────────────────────────

@router.post("/{job_id}/generate", response_model=DevcontainerResponse)
async def generate_devcontainer(
    job_id: int,
    request: DevcontainerRequest,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[dict, Depends(get_current_user)],
):
    """Generate a devcontainer for a completed Atlas job.

    The detected stack from the analysis is used to pick the base image,
    features, and post-create commands. Request body allows overrides.
    """
    org_id: str = current_user["login"]

    # 1. Fetch job (with Repo relationship for URL)
    stmt = select(AtlasJob).options(selectinload(AtlasJob.repo)).where(AtlasJob.id == job_id)
    job = (await db.execute(stmt)).scalar_one_or_none()
    if not job:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Job not found")

    repo_url: str | None = None
    if job.repo:
        repo_url = f"https://github.com/{job.repo.github_owner}/{job.repo.github_repo}"

    # 2. Fetch analysis result for stack detection
    result_row = (
        await db.execute(select(AtlasResult).where(AtlasResult.job_id == job_id))
    ).scalar_one_or_none()

    languages = request.languages
    frameworks: list[str] = []
    evidence: dict | None = None

    if result_row:
        if result_row.detected_stack:
            detected_langs = _languages_from_stack(result_row.detected_stack)
            detected_fw = _frameworks_from_stack(result_row.detected_stack)
            if not languages:
                languages = detected_langs
            frameworks = detected_fw
        # Pass the stored evidence snapshot to the LLM for richer generation.
        # Decrypt first — raw_evidence may be encrypted at rest.
        if result_row.raw_evidence:
            plain = decrypt_json(result_row.raw_evidence)
            evidence = plain[0] if isinstance(plain, list) and plain else plain

    languages = languages or ["python"]

    # 3. Generate devcontainer config (LLM-enhanced, with deterministic fallback)
    config_dict = await _build_config_dict(
        evidence=evidence,
        languages=languages,
        frameworks=frameworks,
        services=request.services,
        custom_features=request.features,
    )

    # 4. Determine next version number for this job
    latest_stmt = (
        select(Devcontainer)
        .where(Devcontainer.job_id == job_id)
        .order_by(Devcontainer.version_number.desc())
        .limit(1)
    )
    latest = (await db.execute(latest_stmt)).scalar_one_or_none()
    next_version = (latest.version_number + 1) if latest else 1

    # Features list: either the LLM's features dict keys, or a fallback list
    features_list = list(config_dict.get("features", {}).keys()) if isinstance(config_dict.get("features"), dict) else []

    # 5. Persist
    dc = Devcontainer(
        job_id=job_id,
        org_id=org_id,
        version_number=next_version,
        config=config_dict,
        features=features_list,
        repo_url=repo_url,
    )
    db.add(dc)
    await db.flush()

    # 6. Audit
    try:
        await AuditService.log_action(
            db,
            action="generated_devcontainer",
            org_id=org_id,
            user_id=current_user["login"],
            resource_type="devcontainer",
            resource_id=dc.id,
            details={"job_id": job_id, "languages": languages, "version": next_version},
        )
    except Exception:
        pass

    await db.commit()

    return DevcontainerResponse(
        devcontainer_id=dc.id,
        job_id=job_id,
        version_number=next_version,
        config=config_dict,
        repo_url=repo_url,
        created_at=dc.created_at,
    )


@router.get("/{job_id}/versions", response_model=DevcontainerListResponse)
async def get_devcontainer_versions(
    job_id: int,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[dict, Depends(get_current_user)],
):
    """Return all devcontainer versions for a job, newest first."""
    stmt = (
        select(Devcontainer)
        .where(Devcontainer.job_id == job_id)
        .order_by(Devcontainer.version_number.desc())
    )
    versions = (await db.execute(stmt)).scalars().all()

    if not versions:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="No devcontainers found for job")

    return DevcontainerListResponse(
        job_id=job_id,
        versions=[
            DevcontainerVersionResponse(
                version_number=v.version_number,
                created_at=v.created_at,
                config=v.config,
            )
            for v in versions
        ],
        latest_version=versions[0].version_number,
    )


@router.get("/{job_id}/download")
async def download_devcontainer(
    job_id: int,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[dict, Depends(get_current_user)],
    version: int = 1,
):
    """Download a devcontainer as a ZIP containing devcontainer.json and setup.sh."""
    stmt = (
        select(Devcontainer)
        .where(Devcontainer.job_id == job_id, Devcontainer.version_number == version)
        .limit(1)
    )
    dc = (await db.execute(stmt)).scalar_one_or_none()
    if not dc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Devcontainer version not found")

    try:
        await AuditService.log_action(
            db,
            action="downloaded_devcontainer",
            org_id=current_user["login"],
            user_id=current_user["login"],
            resource_type="devcontainer",
            resource_id=dc.id,
            details={"job_id": job_id, "version": version},
        )
        await db.commit()
    except Exception:
        pass

    buf = _build_zip(dc.config, version)
    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f'attachment; filename="devcontainer-v{version}.zip"'},
    )


@router.put("/{job_id}/versions/{version_number}", response_model=DevcontainerResponse)
async def update_devcontainer_version(
    job_id: int,
    version_number: int,
    request: DevcontainerRequest,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[dict, Depends(get_current_user)],
):
    """Create a new version based on an existing one with custom overrides."""
    stmt = (
        select(Devcontainer)
        .where(Devcontainer.job_id == job_id, Devcontainer.version_number == version_number)
        .limit(1)
    )
    current = (await db.execute(stmt)).scalar_one_or_none()
    if not current:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Version not found")

    upd_config_dict = await _build_config_dict(
        evidence=None,  # updates use deterministic path; no re-fetch
        languages=request.languages or ["python"],
        frameworks=[],
        services=request.services,
        custom_features=request.features,
    )
    upd_features = list(upd_config_dict.get("features", {}).keys()) if isinstance(upd_config_dict.get("features"), dict) else []

    new_dc = Devcontainer(
        job_id=job_id,
        org_id=current_user["login"],
        version_number=version_number + 1,
        config=upd_config_dict,
        features=upd_features,
        repo_url=current.repo_url,
    )
    db.add(new_dc)
    await db.flush()

    try:
        await AuditService.log_action(
            db,
            action="updated_devcontainer",
            org_id=current_user["login"],
            user_id=current_user["login"],
            resource_type="devcontainer",
            resource_id=new_dc.id,
            details={"job_id": job_id, "new_version": version_number + 1},
        )
    except Exception:
        pass

    await db.commit()

    return DevcontainerResponse(
        devcontainer_id=new_dc.id,
        job_id=job_id,
        version_number=new_dc.version_number,
        config=upd_config_dict,
        repo_url=current.repo_url,
        created_at=new_dc.created_at,
    )
