import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use — CodebaseAtlas",
  description: "Terms governing use of CodebaseAtlas. Public repositories, acceptable use, AI accuracy disclaimer.",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-20">

      {/* Header */}
      <div className="mb-12">
        <div className="flex items-center gap-3 mb-6">
          <span className="font-mono text-[10px] tracking-[0.3em] text-[#c8a96e] uppercase">Legal</span>
          <span className="h-px w-8 bg-[#1e1e1e]" />
        </div>
        <h1 className="font-serif text-5xl text-[#e8e0d4] mb-4">Terms of Use</h1>
        <p className="font-mono text-[11px] text-[#3a3a3a]">Last updated: March 2026</p>
      </div>

      <div className="space-y-10 font-sans text-[14px] text-[#5a5a5a] leading-relaxed">

        <Section title="Acceptance">
          <p>
            By using CodebaseAtlas (available at codebaseatlas.com), you agree to these
            Terms of Use. If you do not agree, please do not use the service.
          </p>
        </Section>

        <Section title="What CodebaseAtlas is">
          <p>
            CodebaseAtlas is a developer tool that fetches and analyzes <strong className="text-[#c8c0b8]">publicly
            accessible</strong> GitHub and GitLab repositories. It generates architecture
            diagrams, framework summaries, API surface maps, and quality assessments using
            a combination of deterministic parsing and AI-generated text (powered by
            Anthropic Claude).
          </p>
        </Section>

        <Section title="Acceptable use">
          <p>You agree to use CodebaseAtlas only for lawful purposes. Specifically, you agree:</p>
          <ul className="mt-3 space-y-2 list-none">
            <Li>To submit only <strong className="text-[#c8c0b8]">public repositories</strong> you have a right to analyze</Li>
            <Li>Not to attempt to abuse the service through automated bulk requests or denial-of-service attacks</Li>
            <Li>Not to attempt to reverse-engineer or circumvent any rate limiting or access controls</Li>
            <Li>Not to use the service to generate analysis that is then misrepresented as original human research</Li>
          </ul>
        </Section>

        <Section title="AI-generated content disclaimer">
          <p>
            Portions of the output (architecture summaries, Mermaid diagrams, endpoint descriptions,
            quality verdicts) are generated by a large language model (Anthropic Claude). This output
            is provided for informational and convenience purposes only.
          </p>
          <p className="mt-3">
            <strong className="text-[#c8c0b8]">AI-generated content may be inaccurate, incomplete, or misleading.</strong>{" "}
            Do not rely on CodebaseAtlas output for security audits, compliance decisions,
            financial evaluations, or any context where accuracy is critical without independent
            verification. Framework detection and dependency parsing are deterministic and generally
            reliable; AI-generated text is not.
          </p>
        </Section>

        <Section title="Rate limiting">
          <p>
            CodebaseAtlas enforces rate limits to ensure fair access and service stability.
            Exceeding these limits will result in temporary request blocking (HTTP 429).
            If you require higher throughput, consider self-hosting — the full source is
            available under the AGPL-3.0 license.
          </p>
        </Section>

        <Section title="Availability and warranty">
          <p>
            CodebaseAtlas is provided <strong className="text-[#c8c0b8]">&ldquo;as is&rdquo;</strong> without any warranty,
            express or implied. We make no guarantees about uptime, accuracy of results,
            or continued availability of any specific feature. The service may be modified,
            restricted, or discontinued at any time.
          </p>
        </Section>

        <Section title="Open source license">
          <p>
            CodebaseAtlas is open-source software released under the{" "}
            <a
              href="https://github.com/MentalVibez/AI_Architecture_Explainer/blob/main/LICENSE"
              target="_blank"
              rel="noopener noreferrer"
              className="text-[#c8a96e] hover:text-[#d4b87a] transition-colors"
            >
              GNU Affero General Public License v3.0 (AGPL-3.0) ↗
            </a>.
          </p>
          <p className="mt-3">
            This means you are free to view, fork, and run the code yourself. If you modify
            and deploy the software as a network service, you must make your modifications
            available under the same license. The hosted version at codebaseatlas.com
            satisfies this requirement by maintaining a public GitHub repository.
          </p>
        </Section>

        <Section title="Limitation of liability">
          <p>
            To the maximum extent permitted by applicable law, CodebaseAtlas and its
            contributors shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages arising from your use of the service,
            including but not limited to loss of data, business interruption, or
            reliance on AI-generated output.
          </p>
        </Section>

        <Section title="Changes">
          <p>
            These terms may be updated at any time. The &ldquo;Last updated&rdquo; date above reflects
            the most recent revision. Continued use of the service after changes constitutes
            acceptance of the updated terms.
          </p>
        </Section>

        <div className="border-t border-[#1a1a1a] pt-8">
          <p className="font-mono text-[11px] text-[#3a3a3a]">
            Questions?{" "}
            <a
              href="https://github.com/MentalVibez/AI_Architecture_Explainer/issues"
              target="_blank"
              rel="noopener noreferrer"
              className="text-[#c8a96e] hover:text-[#d4b87a] transition-colors"
            >
              Open an issue on GitHub ↗
            </a>
          </p>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="border-t border-[#1a1a1a] pt-8">
      <h2 className="font-serif text-2xl text-[#e8e0d4] mb-4">{title}</h2>
      {children}
    </div>
  );
}

function Li({ children }: { children: React.ReactNode }) {
  return (
    <li className="flex gap-2">
      <span className="text-[#2a2a2a] mt-0.5 shrink-0">—</span>
      <span>{children}</span>
    </li>
  );
}
