import type {
  CodebaseGuide,
  ConceptNote,
  ReadingPathItem,
  RiskNote,
  SetupBlocker,
  StarterTask,
  WeekPlanItem,
} from "@/lib/types";

function confidenceLabel(score: number): string {
  if (score >= 0.8) return "high";
  if (score >= 0.5) return "medium";
  return "low";
}

function weekPlanSection(items: WeekPlanItem[]): string {
  if (!items.length) return "";
  const lines = ["## Investigation Plan", ""];
  for (const item of items) {
    lines.push(`### ${item.phase} — ${item.title}`, "");
    if (item.goal) lines.push(`**Goal:** ${item.goal}`, "");
    if (item.actions.length) {
      lines.push("**Actions:**");
      for (const action of item.actions) lines.push(`- ${action}`);
      lines.push("");
    }
  }
  return lines.join("\n");
}

function readingPathSection(items: ReadingPathItem[]): string {
  if (!items.length) return "";
  const lines = ["## Reading Path", ""];
  items.forEach((item, i) => {
    lines.push(`${i + 1}. \`${item.path}\` *(confidence: ${confidenceLabel(item.confidence)})*`);
    if (item.reason) lines.push(`   > ${item.reason}`);
    lines.push("");
  });
  return lines.join("\n");
}

function conceptsSection(items: ConceptNote[]): string {
  if (!items.length) return "";
  const lines = ["## Key Concepts", ""];
  for (const concept of items) {
    lines.push(`### ${concept.name}`, "");
    lines.push(concept.explanation, "");
    if (concept.evidence.length) {
      lines.push(`*Evidence: ${concept.evidence.join(", ")}*`, "");
    }
  }
  return lines.join("\n");
}

function starterTasksSection(items: StarterTask[]): string {
  if (!items.length) return "";
  const lines = ["## Starter Tasks", ""];
  for (const task of items) {
    lines.push(`### ${task.title}`, "");
    if (task.why_safe) lines.push(task.why_safe, "");
    if (task.suggested_checks.length) {
      lines.push("**Checks:**");
      for (const check of task.suggested_checks) lines.push(`- [ ] ${check}`);
      lines.push("");
    }
    if (task.related_paths.length) {
      lines.push(`**Related files:** ${task.related_paths.map((p) => `\`${p}\``).join(", ")}`, "");
    }
  }
  return lines.join("\n");
}

function riskNotesSection(items: RiskNote[]): string {
  if (!items.length) return "";
  const lines = ["## Risk Notes", ""];
  for (const note of items) {
    lines.push(`### ${note.title}`, "");
    lines.push(note.guidance, "");
    if (note.related_paths.length) {
      lines.push(`**Related files:** ${note.related_paths.map((p) => `\`${p}\``).join(", ")}`, "");
    }
  }
  return lines.join("\n");
}

function setupBlockersSection(items: SetupBlocker[]): string {
  if (!items.length) return "";
  const lines = ["## Setup Checklist", ""];
  for (const blocker of items) {
    const severity = blocker.severity ? ` *(${blocker.severity})*` : "";
    lines.push(`- [ ] **${blocker.title}**${severity}`);
    if (blocker.guidance) lines.push(`  > ${blocker.guidance}`);
  }
  lines.push("");
  return lines.join("\n");
}

function questionsSection(title: string, questions: string[]): string {
  if (!questions.length) return "";
  const lines = [`## ${title}`, ""];
  for (const q of questions) lines.push(`- ${q}`);
  lines.push("");
  return lines.join("\n");
}

export function guideToMarkdown(guide: CodebaseGuide, repoLabel?: string | null): string {
  const heading = repoLabel ? `# Onboarding Guide: ${repoLabel}` : "# Onboarding Guide";
  const generated = `*Generated by [CodebaseAtlas](https://www.codebaseatlas.com)*`;

  const sections = [
    `${heading}\n\n${generated}`,
    guide.overview ? `## Overview\n\n${guide.overview}` : "",
    setupBlockersSection(guide.setup_blockers),
    weekPlanSection(guide.week_plan),
    readingPathSection(guide.reading_path),
    conceptsSection(guide.concepts),
    starterTasksSection(guide.starter_tasks),
    riskNotesSection(guide.risk_notes),
    questionsSection("Questions for Your Mentor", guide.mentor_questions),
    questionsSection("Questions for the Team", guide.team_questions),
  ].filter(Boolean);

  return sections.join("\n\n") + "\n";
}
